"""added models

Revision ID: 6720720da3fa
Revises: d4410b0426c6
Create Date: 2025-12-17 14:34:24.244767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6720720da3fa'
down_revision: Union[str, Sequence[str], None] = 'd4410b0426c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credentials_email'), 'user_credentials', ['email'], unique=True)
    op.create_index(op.f('ix_user_credentials_id'), 'user_credentials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credentials_id'), table_name='user_credentials')
    op.drop_index(op.f('ix_user_credentials_email'), table_name='user_credentials')
    op.drop_table('user_credentials')
    # ### end Alembic commands ###
