"""add token_version and user_type to user_credentials

Revision ID: bf3588cbfeff
Revises: 6720720da3fa
Create Date: 2025-12-20 14:12:02.950014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3588cbfeff'
down_revision: Union[str, Sequence[str], None] = '6720720da3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('user_credentials', sa.Column('user_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'user_type')
    op.drop_column('user_credentials', 'token_version')
    # ### end Alembic commands ###
