"""init

Revision ID: c1586024c6a4
Revises: 
Create Date: 2025-11-24 17:46:39.561395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1586024c6a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('seats_per_row', sa.Integer(), nullable=False),
    sa.Column('grid', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_seat_layouts_id'), 'seat_layouts', ['id'], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('seat_layout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seat_layout_id'], ['seat_layouts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_screens_id'), 'screens', ['id'], unique=False)
    op.create_index(op.f('ix_screens_seat_layout_id'), 'screens', ['seat_layout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screens_seat_layout_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_seat_layouts_id'), table_name='seat_layouts')
    op.drop_table('seat_layouts')
    # ### end Alembic commands ###
