"""reservation model added

Revision ID: c47d2ca95426
Revises: 9f9da615f674
Create Date: 2025-12-02 16:34:49.812720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47d2ca95426'
down_revision: Union[str, Sequence[str], None] = '9f9da615f674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', name='Reservation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_index('ix_reservations_showtime_seat', 'reservations', ['showtime_id', 'seat_code'], unique=False)
    op.create_table('seat_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_code', sa.String(length=10), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOCKED', 'RESERVED', name='statusenum'), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('showtime_id', 'seat_code', name='uq_showtime_seat')
    )
    op.create_index('idx_seatlock_lock_expires', 'seat_locks', ['lock_expires_at'], unique=False)
    op.create_index('idx_seatlock_showtime', 'seat_locks', ['showtime_id'], unique=False)
    op.create_index(op.f('ix_seat_locks_id'), 'seat_locks', ['id'], unique=False)
    op.create_index(op.f('ix_seat_locks_seat_code'), 'seat_locks', ['seat_code'], unique=False)
    op.create_index(op.f('ix_seat_locks_status'), 'seat_locks', ['status'], unique=False)
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_seat_locks_status'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_seat_code'), table_name='seat_locks')
    op.drop_index(op.f('ix_seat_locks_id'), table_name='seat_locks')
    op.drop_index('idx_seatlock_showtime', table_name='seat_locks')
    op.drop_index('idx_seatlock_lock_expires', table_name='seat_locks')
    op.drop_table('seat_locks')
    op.drop_index('ix_reservations_showtime_seat', table_name='reservations')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
