"""fix refund request model

Revision ID: d696d2cb72e4
Revises: c2355e971d6c
Create Date: 2025-12-30 17:34:17.301029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd696d2cb72e4'
down_revision: Union[str, Sequence[str], None] = 'c2355e971d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('payment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='refund_request_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('provider_refund_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_requests_id'), 'refund_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ISSUED', 'FAILED', name='refund_status'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], name=op.f('refunds_payment_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('refunds_reservation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey'))
    )
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=False)
    op.drop_index(op.f('ix_refund_requests_id'), table_name='refund_requests')
    op.drop_table('refund_requests')
    # ### end Alembic commands ###
